
stages:
- build
- test

environment setup:
  stage: build
  script:
    - which python3

sast:
  stage: test
  script:
    - echo "this is a sast test"

sca:
  stage: test
  script:
    - echo "this is a sca test"

built-in setting check:
  stage: test 
  script: 
    - echo "this is setting checking"

include:
  - template: Security/SAST.gitlab-ci.yml